services:
  - type: web
    name: sql-injection-game
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    disk:
      name: database
      mountPath: /data
      sizeGB: 1
